name: xLayers CI
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
        version: ['insiders']

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
         
      - name: Install Dependencies
        run: npm install

      - name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run tests
        env:
          CODE_VERSION: ${{ matrix.version }}
          DISPLAY: ':99.0'
        run: npm run test
      